name: Perform Bloodhound Scans
on: [push]
jobs:
  Perform-Bloodhound-Scans:
    runs-on: ubuntu-latest
    container: securestackau/bloodhound-cli:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'
      - name: SecureStack Secrets Scan
        shell: bash
        env:
          BH_APP_ID: ad60440c-8215-478e-a553-8c1d172bf8e8
          BH_API_KEY: ${{ secrets.BH_API_KEY }}
          BH_SEVERITY: critical
        run:
          bloodhound-cli code -s -a $BH_APP_ID
      - name: SecureStack SCA scan
        shell: bash
        env:
          BH_APP_ID: ad60440c-8215-478e-a553-8c1d172bf8e8
          BH_API_KEY: ${{ secrets.BH_API_KEY }}
          BH_SEVERITY: critical
          BH_SCAN_TYPE: node
        run:
          bloodhound-cli code -t $BH_SCAN_TYPE -a $BH_APP_ID --info
      - name: SecureStack web vulnerability scan
        shell: bash
        env:
          BH_APP_ID: ad60440c-8215-478e-a553-8c1d172bf8e8
          BH_API_KEY: ${{ secrets.BH_API_KEY }}
          BH_SEVERITY: critical
        run:
          bloodhound-cli recon -m -r -a $BH_APP_ID
