name: SecureStack All-In-One Action Workflow
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for running secrets analysis within workflow
        id: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          
      - name: SecureStack - Secrets Analysis Step
        id: secrets
        uses: SecureStackCo/actions-secrets@v0.1.3
        with:
          severity: critical
          flags: '-d 50 --info'
          
      - name: SecureStack - Software Composition Analysis Step
        id: code
        uses: SecureStackCo/actions-code@v0.1.1
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
          language: node
          flags: '--info'
      
      - name: SecureStack - Log4j Scanning
        id: log4j
        uses: SecureStackCo/actions-log4j@v0.1.4
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
          
      - name: SecureStack - Web Exposure Analysis Step
        id: exposure
        uses: SecureStackCo/actions-exposure@v0.1.3
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
          flags: '--dom -r --info'
          
      - name: SecureStack - Software Bill of Materials
        id: sbom
        uses: SecureStackCo/actions-abom@v0.1.5
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
        
#      - name: Generate SBOM artifact
#        id: artifact
#        uses: actions/upload-artifact@v3.1.0
#        with:
#          path: ${{ steps.sbom.outputs.fileName }}
#          name: "app.niftybank.org.sbom"
