name: Build javascript app
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo for running secrets analysis within workflow
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm test
