name: Example Workflow Using SecureStack Actions
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to run secrets analysis on it
        id: checkout
        uses: actions/checkout@v2.4.0
      - name: Secrets Analysis Step
        id: secrets
        uses: NiftyBank/niftybank-app/actions/secrets@master
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY_SECRET }}
          securestack_app_id: '8e9778f3-c151-4e82-a446-b945b0d3a15d'
          severity: critical
          flags: '-d 50'
