name: SecureStack Application Bill-of-Materials (ABOM)
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Application Bill-of-Materials Step
        id: exposure
        uses: SecureStackCo/actions-abom@v0.1.3
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: high
          
