name: SecureStack complete GitHub Action - One Action to rule them all!
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for running secrets analysis within workflow
        id: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Secrets Analysis Step
        id: secrets
        uses: SecureStackCo/actions-secrets@v0.1.0
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY_SECRET }}
          securestack_app_id: ad60440c-8215-478e-a553-8c1d172bf8e8
          severity: critical
          flags: '-d 1 -a ad60440c-8215-478e-a553-8c1d172bf8e8'

      - name: Code Analysis Step
        id: code
        uses: SecureStackCo/actions-code@main
        with:
          securestack_api_key: 93627135.VNyjWxf4YHXjVUtg8p6B
          securestack_app_id: ad60440c-8215-478e-a553-8c1d172bf8e8
          severity: high
          language: node
          flags: '--path /github/workspace/ -a ad60440c-8215-478e-a553-8c1d172bf8e8'

      - name: Web Vulnerability Exposure Analysis Step
        id: exposure
        uses: SecureStackCo/actions-exposure@v0.1.2
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY_SECRET }}
          securestack_app_id: ad60440c-8215-478e-a553-8c1d172bf8e83
          severity: critical
          flags: '-r -a ad60440c-8215-478e-a553-8c1d172bf8e8'
  
      - name: Echo 4 variables
        run: |
          echo "securestack_api_key $securestack_api_key securestack_app_id $securestack_app_id BH_API_KEY $BH_API_KEY BH_APP_ID $BH_APP_ID"
        shell: bash
  
