name: SecureStack Secrets Scan Action
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for running secrets analysis within workflow
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'
      - name: Run script file
        run: |
          ls -al
        shell: bash
      - name: Secrets Analysis Step
        id: secrets
        uses: SecureStackCo/actions-secrets@v0.1.0
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY_SECRET }}
          securestack_app_id: 0a25bef3-1920-4bcf-840b-7ff35216b243
          severity: critical
          flags: '-d 1'
